name: Publish to DockerHub 

on:
    push:
        branches:
        - 'main'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Build & Push PyTorch CUDA 10 image
          uses: docker/build-push-action@v2
          with:
              file: docker/Dockerfile.cuda10 
              push: true
              tags: meadml/audio8-gpu:latest
        - name: Build & Push PyTorch CUDA 11 image
          uses: docker/build-push-action@v2
          with:
              file: docker/Dockerfile.cuda11
              push: true
              tags: meadml/audio8-cuda11:latest
        - name: Build & Push PyTorch CUDA 11.1 image
          uses: docker/build-push-action@v2
          with:
              file: docker/Dockerfile.cuda111
              push: true
              tags: meadml/audio8-cuda111:latest

